# Generated by Django 5.2.6 on 2025-10-10 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_policies', to='policy_tracker.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('policy_template', models.TextField(blank=True, null=True)),
                ('getting_processed_for_approval', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organizations', models.ManyToManyField(related_name='policies_linked', through='policy_tracker.OrganizationPolicy', to='policy_tracker.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organizationpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_policies', to='policy_tracker.policy'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationpolicy',
            unique_together={('organization', 'policy')},
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=255)),
                ('diffDetails', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_tracker.policy')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('policy', 'version_number')},
            },
        ),
    ]
