# Generated by Django 5.2.6 on 2025-09-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyversion',
            old_name='content',
            new_name='diffDetails',
        ),
    ]
