# Generated by Django 4.2.24 on 2025-09-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_content_policyversion_diffdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyversion',
            options={'ordering': ('version_number',)},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='policyversion',
            name='diffDetails',
        ),
        migrations.AddField(
            model_name='policy',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policies.organization'),
        ),
        migrations.AddField(
            model_name='policy',
            name='template_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='diff_ops',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='is_checkpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='patch_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='OrganizationPolicy',
        ),
    ]
