# Generated by Django 4.2.24 on 2025-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policyversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('sections', models.JSONField(default=list)),
                ('content', models.TextField()),
            ],
        ),
    ]
