# Generated by Django 4.2.24 on 2025-09-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytemplate',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='policytemplate',
            name='version',
        ),
    ]
