# Generated by Django 4.2.24 on 2025-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_remove_policytemplate_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytemplate',
            name='sections',
            field=models.JSONField(default=list),
        ),
    ]
